# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nico Technical Writing
email: nico.bocalan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nico's technical writing samples, personal projects, and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://peahatlanding.github.io/" # the base hostname & protocol for your site
github_username:  peahatlanding
linkedin_username: Nicolette Bocalan

# Build settings
markdown: kramdown
